name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - run: mvn test-compile -pl JSONCoder -am
      - run:      mvn -pl JSONCoder test -Dtest=org.jsonex.jsoncoder.JSONCoderTest#testEnumNameOption
      - run:      mvn -pl JSONCoder edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.jsonex.jsoncoder.JSONCoderTest#testEnumNameOption -DnondexRuns=10
